name: myHome
version: '1.1'
main: me.zombix.myhome.MyHome
api-version: '1.20'
commands:
  sethome:
    description: Set your home
    usage: /sethome
  home:
    description: Teleport to your home
    usage: /home
  reload:
    description: Reload plugin
    usage: /myhome:reload
  myhome:
    description: myHome plugin command
    usage: /myhome <sethome/home/reload>
    aliases:
      - sethome
      - home
      - reload

permissions:
  myhome.home:
    description: Allow to use /home command
    default: true
  myhome.sethome:
    description: Allow to use /sethome command
    default: true
  myhome.reload:
    description: Allow to use /myhome:reload command
    default: false