name: myHome
version: '${project.version}'
main: me.zombix.myhome.MyHome
api-version: '1.20'
commands:
  sethome:
    description: Set your home
    usage: /sethome
  home:
    description: Teleport to your home
    usage: /home
  homes:
    description: Show player homes list
    usage: /homes
  reload:
    description: Reload plugin
    usage: /myhome reload
  myhome:
    description: myHome plugin command
    usage: /myhome <reload/sethome/home/setdescription> <home_number/description/setdescription/delete> <description/home_number>
    aliases:
      - sethome
      - home
      - setdescription
      - homes
      - reload

permissions:
  myhome.myhome:
    description: Allow to use /myhome command
    default: true
  myhome.home:
    description: Allow to use /home command
    default: true
  myhome.sethome:
    description: Allow to use /sethome command
    default: true
  myhome.reload:
    description: Allow to use /myhome reload command
    default: op
  myhome.homes:
    description: Allow to use /homes command
    default: true
  myhome.setdescription:
    description: Allow to use /home setdescription command
    default: true
  myhome.deletehome:
    description: Allow to use /home delete command
    default: true
  myhome.managepermissions:
    description: Allow to use /myhome addpermission, editpermission, deletepermission command
    default: true