name: myHome
version: '${project.version}'
main: me.zombix.myhome.MyHome
api-version: '1.20'
commands:
  sethome:
    description: Set your home
    usage: /sethome
  home:
    description: Teleport to your home
    usage: /home

permissions:
  sethomeplugin.home:
    description: Allow to use /home command
    default: true
  sethomeplugin.sethome:
    description: Allow to use /sethome command
    default: true